import type { Category, Keyword } from "./types";

export const seedCategories: Category[] = [
  { id: 1, slug: "pets", name: "Pets", description: "Pet care, training, food, and supplies keywords", icon: "pets", keyword_count: 5, created_at: "2025-01-01" },
  { id: 2, slug: "health", name: "Health & Fitness", description: "Wellness, fitness, nutrition, and medical keywords", icon: "health", keyword_count: 5, created_at: "2025-01-01" },
  { id: 3, slug: "finance", name: "Finance", description: "Investing, saving, credit, and money management", icon: "finance", keyword_count: 5, created_at: "2025-01-01" },
  { id: 4, slug: "food", name: "Food & Cooking", description: "Recipes, cooking techniques, diets, and food reviews", icon: "food", keyword_count: 5, created_at: "2025-01-01" },
  { id: 5, slug: "tech", name: "Technology", description: "Software, gadgets, AI tools, and programming", icon: "tech", keyword_count: 5, created_at: "2025-01-01" },
  { id: 6, slug: "home", name: "Home & DIY", description: "Home improvement, decoration, and DIY projects", icon: "home", keyword_count: 5, created_at: "2025-01-01" },
  { id: 7, slug: "travel", name: "Travel", description: "Destinations, tips, gear, and travel planning", icon: "travel", keyword_count: 5, created_at: "2025-01-01" },
  { id: 8, slug: "education", name: "Education", description: "Online courses, learning resources, and study tips", icon: "education", keyword_count: 4, created_at: "2025-01-01" },
  { id: 9, slug: "beauty", name: "Beauty & Skincare", description: "Skincare, makeup, hair care, and beauty reviews", icon: "beauty", keyword_count: 4, created_at: "2025-01-01" },
  { id: 10, slug: "business", name: "Business & Marketing", description: "Entrepreneurship, marketing, and small business tips", icon: "business", keyword_count: 4, created_at: "2025-01-01" },
  { id: 11, slug: "sports", name: "Sports & Fitness", description: "Training, gear, and sports performance", icon: "sports", keyword_count: 4, created_at: "2025-01-01" },
  { id: 12, slug: "automotive", name: "Automotive", description: "Car maintenance, buying guides, and accessories", icon: "automotive", keyword_count: 3, created_at: "2025-01-01" },
  { id: 13, slug: "gardening", name: "Gardening", description: "Plants, landscaping, and garden care", icon: "gardening", keyword_count: 4, created_at: "2025-01-01" },
  { id: 14, slug: "parenting", name: "Parenting", description: "Baby care, child development, and family life", icon: "parenting", keyword_count: 4, created_at: "2025-01-01" },
  { id: 15, slug: "fashion", name: "Fashion", description: "Style guides, trends, and clothing reviews", icon: "fashion", keyword_count: 3, created_at: "2025-01-01" },
];

const S = "stable", U = "up", D = "down";
const _faq = (q: string, a: string) => ({ q, a });

export const seedKeywords: Keyword[] = [
  // ── Pets (id:1) ────────────────────────────
  { id: 1, slug: "diy-dog-wash-station", keyword: "DIY dog wash station for home", category_id: 1, language: "en", search_volume_estimate: 2400, trend_direction: U, trend_score: 72, competition_score: 15, opportunity_score: 89, result_count: 18000, top_domains: ["pinterest.com", "reddit.com", "youtube.com"], content_suggestion: "Step-by-step guide to building a homemade dog washing station with PVC pipes and a utility sink. Include cost breakdown, tools needed, and before/after photos.", related_keywords: ["homemade dog grooming station", "outdoor dog wash area", "dog bath station ideas", "DIY pet shower"], faq: [_faq("How much does it cost to build a DIY dog wash station?", "A basic DIY dog wash station typically costs $50–200 depending on materials. PVC pipe setups are the cheapest, while tiled stations with plumbing can run $200+.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 2, slug: "best-cat-food-sensitive-stomach", keyword: "best cat food for sensitive stomach vomiting", category_id: 1, language: "en", search_volume_estimate: 5400, trend_direction: S, trend_score: 65, competition_score: 22, opportunity_score: 82, result_count: 45000, top_domains: ["reddit.com", "chewy.com", "thesprucepets.com"], content_suggestion: "Vet-reviewed comparison of top 10 cat foods for sensitive stomachs. Include ingredient analysis, price per day, and a printable shopping guide.", related_keywords: ["limited ingredient cat food", "grain free cat food", "wet food for cats with IBS", "best dry food for digestive issues"], faq: [_faq("What ingredients cause stomach sensitivity in cats?", "Common triggers include grains like wheat and corn, artificial preservatives, dairy, and certain proteins like beef. Limited-ingredient diets help identify the trigger.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 51, slug: "puppy-training-schedule-by-age", keyword: "puppy training schedule by age week by week", category_id: 1, language: "en", search_volume_estimate: 3800, trend_direction: U, trend_score: 68, competition_score: 18, opportunity_score: 86, result_count: 15000, top_domains: ["akc.org", "reddit.com", "pinterest.com"], content_suggestion: "Week-by-week training milestones from 8 weeks to 1 year. Printable checklist for each stage covering potty training, commands, socialization, and leash walking.", related_keywords: ["8 week old puppy training", "puppy potty training schedule", "puppy socialization checklist", "dog training timeline"], faq: [_faq("At what age should puppy training start?", "Basic training can begin as early as 8 weeks old. Focus on socialization, potty training, and simple commands like 'sit' and 'come' in the first few weeks.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 52, slug: "homemade-dog-food-crockpot", keyword: "homemade dog food crockpot recipe vet approved", category_id: 1, language: "en", search_volume_estimate: 2100, trend_direction: U, trend_score: 60, competition_score: 12, opportunity_score: 87, result_count: 9000, top_domains: ["allrecipes.com", "pinterest.com", "youtube.com"], content_suggestion: "5 vet-approved slow cooker dog food recipes with nutritional breakdowns. Include ingredient substitutions for allergies and portion calculator by dog weight.", related_keywords: ["easy homemade dog food", "slow cooker pet food", "healthy dog food recipes", "DIY dog food nutrition"], faq: [_faq("Is homemade dog food healthier than kibble?", "Homemade dog food can be healthier when properly balanced with protein, carbs, and vegetables. However, it must include essential nutrients like calcium and taurine — consult your vet for a balanced recipe.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Health & Fitness (id:2) ─────────────────
  { id: 3, slug: "couch-to-5k-plan-for-seniors", keyword: "couch to 5K plan for seniors over 60", category_id: 2, language: "en", search_volume_estimate: 3200, trend_direction: U, trend_score: 78, competition_score: 8, opportunity_score: 93, result_count: 12000, top_domains: ["verywellfit.com", "reddit.com"], content_suggestion: "A 12-week running plan for seniors emphasizing joint safety, heart rate zones, and recovery. Include doctor-check tips, recommended shoes, and a printable progress tracker.", related_keywords: ["walking to running program seniors", "senior fitness plan", "running after 60", "safe running for older adults"], faq: [_faq("Is running safe for a 60-year-old beginner?", "Yes, with proper preparation. Consult your doctor, invest in good shoes, and start with brisk walking before introducing run intervals. Many seniors successfully complete C25K programs.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 53, slug: "intermittent-fasting-for-women-over-40", keyword: "intermittent fasting for women over 40 meal plan", category_id: 2, language: "en", search_volume_estimate: 6200, trend_direction: U, trend_score: 84, competition_score: 28, opportunity_score: 80, result_count: 38000, top_domains: ["healthline.com", "reddit.com", "mindbodygreen.com"], content_suggestion: "Hormone-aware intermittent fasting guide for perimenopausal women. 16:8 and 14:10 protocols with sample meal plans, supplement recommendations, and a 30-day kickstart calendar.", related_keywords: ["IF for menopause", "fasting over 40 female", "hormone balance diet plan", "best fasting schedule for women"], faq: [_faq("Does intermittent fasting work for women over 40?", "Yes, but timing matters. A 14:10 schedule is often gentler on hormones than 16:8 for perimenopausal women. Focus on protein-rich meals and avoid fasting during the week before your period.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 54, slug: "best-yoga-poses-for-back-pain", keyword: "best yoga poses for lower back pain beginners", category_id: 2, language: "en", search_volume_estimate: 8800, trend_direction: S, trend_score: 62, competition_score: 35, opportunity_score: 72, result_count: 92000, top_domains: ["yogajournal.com", "verywellfit.com", "healthline.com"], content_suggestion: "Illustrated guide to 10 gentle yoga poses for lower back pain. Each pose with modifications for limited mobility, safety warnings, and a 15-minute daily routine video script.", related_keywords: ["gentle yoga for back", "morning yoga routine", "yoga for sciatica", "stretches for back pain"], faq: [_faq("Which yoga poses should I avoid with lower back pain?", "Avoid deep forward folds, full wheel pose, and unsupported twists. Focus on cat-cow, child's pose, and gentle supine stretches. Always work within a pain-free range of motion.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Finance (id:3) ──────────────────────────
  { id: 4, slug: "high-dividend-etf-monthly-payout", keyword: "high dividend ETF monthly payout 2025", category_id: 3, language: "en", search_volume_estimate: 8100, trend_direction: U, trend_score: 85, competition_score: 30, opportunity_score: 78, result_count: 89000, top_domains: ["investopedia.com", "fool.com", "seekingalpha.com"], content_suggestion: "Curated list of monthly dividend ETFs with yield, expense ratio, and 5-year performance. Interactive comparison table and downloadable spreadsheet. Tax implications for non-US investors.", related_keywords: ["best monthly dividend ETFs", "high yield income ETFs", "monthly dividend stocks", "ETF with 5% yield"], faq: [_faq("Which ETF pays the highest monthly dividend?", "As of 2025, JEPI, JEPQ, and DIVO are among the highest-yielding monthly-pay ETFs with yields in the 7–10% range. Total return and expense ratio matter as much as yield.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 55, slug: "best-credit-card-for-freelancers", keyword: "best credit card for freelancers 2025 no annual fee", category_id: 3, language: "en", search_volume_estimate: 2700, trend_direction: U, trend_score: 71, competition_score: 20, opportunity_score: 83, result_count: 22000, top_domains: ["nerdwallet.com", "reddit.com", "forbes.com"], content_suggestion: "Compare top 8 no-annual-fee cards for freelancers: cashback on business expenses, virtual card features, expense tracking integrations, and 0% intro APR periods. Decision flowchart included.", related_keywords: ["freelancer banking tips", "self employed credit card", "business card no fee", "best cashback for freelancers"], faq: [_faq("Should freelancers get a business credit card?", "Yes, even sole proprietors benefit. Business cards separate personal and business expenses for tax time, often have higher credit limits, and may offer expense-management features useful for freelancers.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 56, slug: "how-to-build-emergency-fund-fast", keyword: "how to build an emergency fund fast on low income", category_id: 3, language: "en", search_volume_estimate: 4100, trend_direction: U, trend_score: 75, competition_score: 15, opportunity_score: 85, result_count: 18000, top_domains: ["reddit.com", "daveramsey.com", "thepennyhoarder.com"], content_suggestion: "Realistic 90-day plan to save $1000 emergency fund on a tight budget. Side hustle ideas ranked by effort-to-reward, automatic savings hacks, and a printable savings tracker.", related_keywords: ["save money fast", "emergency fund calculator", "low income savings plan", "how much emergency fund"], faq: [_faq("How much should I have in an emergency fund?", "Aim for 3–6 months of essential expenses. Start with a mini-goal of $1000, then build to one month of expenses, then expand from there. Any emergency fund is better than none.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Food & Cooking (id:4) ───────────────────
  { id: 5, slug: "sourdough-discard-crackers-recipe", keyword: "sourdough discard crackers recipe easy", category_id: 4, language: "en", search_volume_estimate: 9800, trend_direction: U, trend_score: 90, competition_score: 25, opportunity_score: 85, result_count: 56000, top_domains: ["kingarthurbaking.com", "pinterest.com", "theclevercarrot.com"], content_suggestion: "Ultimate guide to sourdough discard crackers with 5 flavor variations. Step-by-step photos, storage tips, and a video embed. Pairing suggestions for cheese boards.", related_keywords: ["sourdough discard recipes", "what to make with sourdough discard", "easy sourdough crackers", "no-waste sourdough ideas"], faq: [_faq("Can I freeze sourdough discard crackers?", "Yes, baked crackers freeze well for up to 3 months. You can also freeze the dough disc and bake fresh later.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 57, slug: "meal-prep-ideas-for-weight-loss", keyword: "healthy meal prep ideas for weight loss on a budget", category_id: 4, language: "en", search_volume_estimate: 7200, trend_direction: U, trend_score: 77, competition_score: 32, opportunity_score: 75, result_count: 61000, top_domains: ["eatingwell.com", "pinterest.com", "reddit.com"], content_suggestion: "Budget-friendly meal prep for weight loss: 5 complete weekly plans under $50 each. Calorie counts, grocery lists, container recommendations, and freezer-friendly options.", related_keywords: ["cheap meal prep", "low calorie meal prep", "weight loss lunch ideas", "budget healthy eating plan"], faq: [_faq("How long can meal prep food stay in the fridge?", "Most cooked meals stay fresh for 3–4 days refrigerated. Prep twice a week if you prefer fresher food, or freeze half the batch for later in the week.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 58, slug: "air-fryer-recipes-for-beginners", keyword: "easy air fryer recipes for beginners healthy", category_id: 4, language: "en", search_volume_estimate: 11500, trend_direction: U, trend_score: 88, competition_score: 38, opportunity_score: 70, result_count: 87000, top_domains: ["delish.com", "tasteofhome.com", "allrecipes.com"], content_suggestion: "25 beginner-friendly air fryer recipes organized by meal type. Cooking time cheat sheet for common foods, cleaning tips, and the 5 mistakes every new air fryer owner makes.", related_keywords: ["air fryer cooking guide", "quick air fryer meals", "healthy air fryer snacks", "air fryer vegetables recipe"], faq: [_faq("Do I need to preheat an air fryer?", "Most air fryers benefit from 2–3 minutes of preheating for crispier results. However, some models don't require it — check your manual. Generally, preheat for meats and frozen foods, skip for baked goods.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Tech (id:5) ─────────────────────────────
  { id: 6, slug: "cursor-ai-vs-copilot-2025", keyword: "Cursor AI vs GitHub Copilot 2025 comparison", category_id: 5, language: "en", search_volume_estimate: 6200, trend_direction: U, trend_score: 95, competition_score: 35, opportunity_score: 76, result_count: 67000, top_domains: ["medium.com", "reddit.com", "youtube.com"], content_suggestion: "Head-to-head comparison based on real coding tasks: autocomplete accuracy, refactoring quality, context understanding, and price. Side-by-side screenshots and a verdict table.", related_keywords: ["best AI coding assistant 2025", "Cursor AI review", "GitHub Copilot X", "AI code editor comparison"], faq: [_faq("Is Cursor better than GitHub Copilot?", "Cursor offers deeper IDE integration and context awareness for large codebases. Copilot has broader language support and a larger community. For full-stack work, many developers prefer Cursor in 2025.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 59, slug: "best-password-manager-for-families", keyword: "best password manager for families 2025 comparison", category_id: 5, language: "en", search_volume_estimate: 3500, trend_direction: S, trend_score: 55, competition_score: 25, opportunity_score: 74, result_count: 31000, top_domains: ["pcmag.com", "reddit.com", "cnet.com"], content_suggestion: "Family-focused password manager comparison: 1Password vs Bitwarden vs Dashlane vs NordPass. Evaluate sharing features, emergency access, child accounts, and price per user.", related_keywords: ["family password sharing", "best free password manager", "password security for families", "1Password family plan review"], faq: [_faq("Can families use a free password manager?", "Bitwarden's free plan supports unlimited devices and basic sharing. For family-specific features like emergency access and admin controls, 1Password Families ($4.99/month for 5) is the best value.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 60, slug: "how-to-speed-up-windows-11", keyword: "how to speed up Windows 11 laptop for free", category_id: 5, language: "en", search_volume_estimate: 9400, trend_direction: S, trend_score: 58, competition_score: 42, opportunity_score: 65, result_count: 102000, top_domains: ["tomshardware.com", "reddit.com", "windowscentral.com"], content_suggestion: "12 no-cost Windows 11 performance tweaks: startup programs, visual effects, background apps, disk cleanup, and power settings. Before/after benchmark data and a one-click PowerShell cleanup script.", related_keywords: ["Windows 11 slow fix", "speed up laptop free", "Windows 11 debloat script", "improve PC performance"], faq: [_faq("Why is Windows 11 so slow on my laptop?", "Common causes: too many startup programs, insufficient RAM (under 8GB), background apps, outdated drivers, or a nearly full SSD. The top 3 fixes — disable startup items, adjust visual effects, and free disk space — solve most cases.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Home & DIY (id:6) ───────────────────────
  { id: 7, slug: "small-bathroom-storage-rental", keyword: "small bathroom storage ideas for renters", category_id: 6, language: "en", search_volume_estimate: 4800, trend_direction: S, trend_score: 55, competition_score: 12, opportunity_score: 88, result_count: 21000, top_domains: ["pinterest.com", "apartmenttherapy.com", "reddit.com"], content_suggestion: "No-drill, landlord-friendly storage solutions by bathroom zone. Amazon product links, IKEA hacks, and a space calculator tool.", related_keywords: ["renter friendly organization", "over toilet storage", "small bathroom shelving", "apartment storage hacks"], faq: [_faq("How to add storage without drilling?", "Tension rods, over-the-door organizers, Command-brand adhesive hooks and shelves, freestanding units, and magnetic strips are all fully reversible options.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 61, slug: "how-to-paint-kitchen-cabinets", keyword: "how to paint kitchen cabinets without sanding", category_id: 6, language: "en", search_volume_estimate: 6700, trend_direction: U, trend_score: 73, competition_score: 20, opportunity_score: 82, result_count: 17000, top_domains: ["pinterest.com", "homedepot.com", "thisoldhouse.com"], content_suggestion: "Complete DIY guide to painting cabinets without sanding using liquid deglosser. Step-by-step video, best paint brands for cabinets, and a 3-day project timeline for a full kitchen.", related_keywords: ["cabinet painting DIY", "no sand cabinet refinish", "best paint for cabinets", "kitchen makeover budget"], faq: [_faq("Does painting cabinets without sanding really work?", "Yes, using a liquid deglosser (like Krud Kutter or Liquid Sandpaper) chemically etches the surface so primer and paint adhere. The finish won't be quite as durable as sanding, but it's 80% of the result for 20% of the effort.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 62, slug: "diy-accent-wall-ideas-bedroom", keyword: "DIY accent wall ideas for bedroom on a budget", category_id: 6, language: "en", search_volume_estimate: 3900, trend_direction: U, trend_score: 66, competition_score: 14, opportunity_score: 86, result_count: 12000, top_domains: ["pinterest.com", "youtube.com", "bhg.com"], content_suggestion: "10 accent wall projects under $100: peel-and-stick wallpaper, wood slats, paint techniques, and board-and-batten. Material lists, time estimates, and rental-friendly removable options.", related_keywords: ["bedroom accent wall paint", "cheap wall decor ideas", "wood slat wall DIY", "peel and stick wallpaper"], faq: [_faq("What is the cheapest way to create an accent wall?", "Paint is the most affordable option at $30-50 for a feature wall. Peel-and-stick wallpaper runs $40-80 for an accent wall. The most impact for the least money: a geometric painted design using painter's tape.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Travel (id:7) ───────────────────────────
  { id: 8, slug: "workation-visa-digital-nomad-2025", keyword: "workation visa digital nomad 2025 countries", category_id: 7, language: "en", search_volume_estimate: 3700, trend_direction: U, trend_score: 82, competition_score: 28, opportunity_score: 79, result_count: 34000, top_domains: ["nomadlist.com", "reddit.com", "thepointsguy.com"], content_suggestion: "Updated 2025 list of digital nomad visa countries with requirements, costs, income thresholds, and tax implications. Comparison table and country-matching quiz.", related_keywords: ["best countries for digital nomads", "nomad visa requirements", "cheapest nomad visa", "remote work visa Europe"], faq: [_faq("Which country has the easiest digital nomad visa?", "Portugal's D8 and Spain's digital nomad visa are among the most accessible, requiring proof of about $3,000/month. Estonia and Croatia also have streamlined online applications.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 63, slug: "budget-travel-japan-itinerary", keyword: "Japan travel itinerary 2 weeks budget 2025", category_id: 7, language: "en", search_volume_estimate: 5500, trend_direction: U, trend_score: 80, competition_score: 30, opportunity_score: 77, result_count: 39000, top_domains: ["reddit.com", "japan-guide.com", "youtube.com"], content_suggestion: "Detailed 14-day Japan itinerary on a $100/day budget. Tokyo-Kyoto-Osaka route with JR Pass calculations, budget hotel picks, affordable food spots, and hidden gems beyond the tourist trail.", related_keywords: ["Japan budget trip", "Tokyo to Kyoto route", "cheap Japan travel tips", "2 week Asia itinerary"], faq: [_faq("How much does a 2-week trip to Japan cost?", "Budget travelers can do Japan for $1,400-2,000 total per person excluding flights. Key savings: JR Pass for long-distance trains, business hotels instead of tourist hotels, and konbini/conveyor-belt meals.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 64, slug: "best-travel-insurance-for-seniors", keyword: "best travel insurance for seniors over 70 with pre-existing conditions", category_id: 7, language: "en", search_volume_estimate: 1800, trend_direction: U, trend_score: 63, competition_score: 10, opportunity_score: 90, result_count: 8000, top_domains: ["squaremouth.com", "reddit.com", "aarp.org"], content_suggestion: "Compare 6 insurers that cover travelers 70+ with pre-existing conditions. Medical evacuation limits, stability-period rules, and a plain-English explanation of what pre-existing condition waivers actually cover.", related_keywords: ["senior travel medical insurance", "over 70 travel cover", "pre-existing condition travel insurance", "best travel insurance for elderly"], faq: [_faq("Can an 80-year-old get travel insurance?", "Yes, several insurers like Allianz, GeoBlue, and Seven Corners offer policies for travelers 80+. Premiums are higher and pre-existing condition coverage requires purchasing within 14-21 days of your first trip payment.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Education (id:8) ────────────────────────
  { id: 9, slug: "notion-template-student-planner", keyword: "free Notion template for student planner", category_id: 8, language: "en", search_volume_estimate: 6600, trend_direction: U, trend_score: 76, competition_score: 20, opportunity_score: 84, result_count: 28000, top_domains: ["reddit.com", "youtube.com", "notion.so"], content_suggestion: "Curated roundup of 15 free Notion student templates with screenshots, setup times, and pros/cons. Tutorial on customization.", related_keywords: ["best Notion templates for college", "Notion student dashboard", "aesthetic Notion templates", "Notion for university"], faq: [_faq("Are free Notion templates worth it?", "Yes, many free templates from experienced creators match paid quality. Start with the official Notion gallery, then check Gumroad and Reddit for community-made options.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 65, slug: "best-online-course-platforms-for-creators", keyword: "best online course platforms for creators 2025 comparison", category_id: 8, language: "en", search_volume_estimate: 3100, trend_direction: U, trend_score: 70, competition_score: 34, opportunity_score: 71, result_count: 48000, top_domains: ["teachable.com", "thinkific.com", "reddit.com"], content_suggestion: "Teachables vs Thinkific vs Kajabi vs Podia vs Gumroad head-to-head. Fee comparison calculator, student-experience walkthrough screenshots, and a launch checklist.", related_keywords: ["sell courses online", "course platform fees", "best LMS for creators", "Kajabi vs Teachable"], faq: [_faq("Which course platform has the lowest fees?", "Gumroad charges no monthly fee but takes 10% per sale. Teachable's free plan takes $1 + 10%. Thinkific has a free plan with 0% transaction fees but limited features. For serious creators, Thinkific's free tier is the best deal.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Beauty (id:9) ───────────────────────────
  { id: 10, slug: "korean-skincare-routine-oily-skin", keyword: "Korean skincare routine for oily skin beginners", category_id: 9, language: "en", search_volume_estimate: 7800, trend_direction: S, trend_score: 60, competition_score: 32, opportunity_score: 73, result_count: 52000, top_domains: ["sokoglam.com", "peachandlily.com", "reddit.com"], content_suggestion: "Adapted 10-step Korean routine for oily skin with drugstore alternatives for every product. Morning vs evening cheat sheet and ingredient checklist.", related_keywords: ["Korean skincare oily acne", "best Korean moisturizer oily", "glass skin routine oily", "Korean skincare combination"], faq: [_faq("Can oily skin do the full 10-step routine?", "Yes, with lightweight gel-based products and no heavy creams. Focus on double cleansing, BHA exfoliation, and oil-free hydration. 5-7 steps are often enough for oily skin.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 66, slug: "best-retinol-for-beginners-sensitive-skin", keyword: "best retinol serum for beginners with sensitive skin", category_id: 9, language: "en", search_volume_estimate: 4200, trend_direction: U, trend_score: 69, competition_score: 24, opportunity_score: 81, result_count: 27000, top_domains: ["reddit.com", "paulaschoice.com", "dermstore.com"], content_suggestion: "Gentle retinol guide for sensitive skin: 8 products ranked by irritation potential, the sandwich method explained, and a 12-week ramp-up calendar. Include bakuchiol as a plant-based alternative.", related_keywords: ["gentle retinol for sensitive skin", "retinol sandwich method", "beginners guide to retinoids", "best drugstore retinol 2025"], faq: [_faq("How often should beginners use retinol?", "Start once every 3 nights for the first 2 weeks, then every other night for 2 weeks, then nightly if tolerated. The sandwich method (moisturizer-retinol-moisturizer) significantly reduces irritation.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Business (id:10) ────────────────────────
  { id: 11, slug: "ai-marketing-automation-small-business", keyword: "AI marketing automation for small business 2025", category_id: 10, language: "en", search_volume_estimate: 4200, trend_direction: U, trend_score: 88, competition_score: 40, opportunity_score: 71, result_count: 78000, top_domains: ["hubspot.com", "zapier.com", "forbes.com"], content_suggestion: "AI tools for email, social scheduling, customer segmentation, and chatbots — all under $50/month. Tools comparison matrix and 30-day implementation roadmap.", related_keywords: ["small business marketing tools", "AI email marketing", "best chatbots small business", "automated social posting AI"], faq: [_faq("How much does AI marketing automation cost?", "Start with free tiers: Mailchimp for email, Buffer for social, Tidio for chat. A full AI-powered stack runs $50-150/month, far less than hiring a marketing team.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 67, slug: "how-to-start-a-newsletter", keyword: "how to start a newsletter and make money 2025", category_id: 10, language: "en", search_volume_estimate: 5100, trend_direction: U, trend_score: 79, competition_score: 36, opportunity_score: 73, result_count: 56000, top_domains: ["substack.com", "reddit.com", "convertkit.com"], content_suggestion: "Complete newsletter launch guide: niche selection framework, platform comparison (Substack vs ConvertKit vs beehiiv), growth tactics for the first 1000 subscribers, and 5 monetization models.", related_keywords: ["start a paid newsletter", "grow email list fast", "newsletter monetization tips", "best newsletter platforms"], faq: [_faq("Can you really make money with a newsletter?", "Yes. Direct revenue models include paid subscriptions (Substack), sponsorships ($25-250 CPM depending on niche), affiliate marketing, and selling your own products. Many creators reach $1k/month within 6-12 months of consistent publishing.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Sports (id:11) ──────────────────────────
  { id: 12, slug: "resistance-band-workout-plan-pdf", keyword: "resistance band workout plan PDF free", category_id: 11, language: "en", search_volume_estimate: 5600, trend_direction: S, trend_score: 58, competition_score: 18, opportunity_score: 83, result_count: 19000, top_domains: ["pinterest.com", "muscleandstrength.com", "reddit.com"], content_suggestion: "Printable 8-week resistance band program with exercise illustrations. Beginner, intermediate, and advanced tracks plus nutrition add-on.", related_keywords: ["full body band workout", "free workout plan PDF", "resistance band exercises chart", "home workout band only"], faq: [_faq("Can you build muscle with only resistance bands?", "Yes, bands provide variable resistance effective for building muscle. Progressive overload is achieved with thicker bands, more reps, or adjusted anchor points.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 68, slug: "home-gym-setup-small-space", keyword: "home gym setup ideas for small space budget 2025", category_id: 11, language: "en", search_volume_estimate: 4500, trend_direction: U, trend_score: 74, competition_score: 22, opportunity_score: 81, result_count: 18000, top_domains: ["reddit.com", "garagegymreviews.com", "youtube.com"], content_suggestion: "Build a functional home gym in 50 sq ft for under $500. Essential equipment ranked by versatility, storage hacks for apartments, and 3 full-body workout routines using minimal gear.", related_keywords: ["small home gym equipment", "apartment workout space", "budget gym setup", "compact exercise equipment"], faq: [_faq("What is the best first piece of home gym equipment?", "Adjustable dumbbells (like PowerBlock or Bowflex) offer the most versatility per square foot and dollar. A close second is a quality pull-up bar with resistance bands for a complete setup under $200.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Automotive (id:12) ──────────────────────
  { id: 13, slug: "ev-battery-replacement-cost-2025", keyword: "EV battery replacement cost 2025 by model", category_id: 12, language: "en", search_volume_estimate: 4400, trend_direction: U, trend_score: 70, competition_score: 45, opportunity_score: 65, result_count: 43000, top_domains: ["recurrentauto.com", "tesla.com", "caranddriver.com"], content_suggestion: "Battery replacement costs for Tesla, Leaf, Bolt, Kona, Mustang Mach-E. Warranty coverage, third-party vs dealer pricing, and battery-life extension tips.", related_keywords: ["Tesla battery replacement cost", "EV battery lifespan", "EV warranty coverage", "cheapest EV battery replacement"], faq: [_faq("How much does EV battery replacement cost?", "In 2025, replacement ranges from $3,000-7,000 for older Nissan Leafs to $12,000-20,000 for Tesla Model S/X. Most modern EVs have 8-year/100,000-mile warranties covering replacement below 70% capacity.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 69, slug: "best-dash-cam-for-night-driving", keyword: "best dash cam for night driving 2025 under 200", category_id: 12, language: "en", search_volume_estimate: 2300, trend_direction: U, trend_score: 67, competition_score: 16, opportunity_score: 84, result_count: 12000, top_domains: ["reddit.com", "youtube.com", "blackboxmycar.com"], content_suggestion: "Night-performance dash cam comparison with real footage comparisons. Installation guide for clean wiring, parking mode setup, and SD card recommendations.", related_keywords: ["best budget dash cam", "night vision dash cam", "dash cam with parking mode", "front and rear dash cam"], faq: [_faq("What makes a dash cam good at night?", "Look for a Sony STARVIS sensor, wide aperture (f/1.8 or lower), and HDR/WDR processing. The VIOFO A119 and Vantrue N4 are consistently ranked as top performers for nighttime clarity under $200.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Gardening (id:13) ───────────────────────
  { id: 14, slug: "raised-garden-bed-vegetable-layout", keyword: "raised garden bed vegetable layout planner", category_id: 13, language: "en", search_volume_estimate: 3300, trend_direction: U, trend_score: 68, competition_score: 14, opportunity_score: 86, result_count: 15000, top_domains: ["almanac.com", "pinterest.com", "reddit.com"], content_suggestion: "Interactive companion planting guide with seasonal rotation plans. Printable layout templates for 4x4, 4x8, and 3x6 beds plus beginner's veggie selection by climate zone.", related_keywords: ["raised bed planting guide", "companion planting chart", "square foot gardening", "vegetable garden planner"], faq: [_faq("What vegetables should not be planted together?", "Avoid planting tomatoes with potatoes, onions with beans, dill with carrots, and fennel with almost anything. Use a companion planting chart for best results.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 70, slug: "indoor-herb-garden-apartment", keyword: "indoor herb garden for apartment beginners no sunlight", category_id: 13, language: "en", search_volume_estimate: 2800, trend_direction: U, trend_score: 71, competition_score: 11, opportunity_score: 89, result_count: 9000, top_domains: ["pinterest.com", "reddit.com", "apartmenttherapy.com"], content_suggestion: "Set up an indoor herb garden in a low-light apartment using grow lights. 8 herbs that thrive indoors, recommended LED setups under $40, watering schedule, and harvesting tips.", related_keywords: ["grow herbs indoors apartment", "best indoor grow lights", "low light herbs kitchen", "beginner herb garden kit"], faq: [_faq("What herbs grow best indoors without sunlight?", "Mint, chives, parsley, and cilantro are the most shade-tolerant culinary herbs. With a budget LED grow light ($20-40), you can also grow basil, oregano, and thyme successfully indoors.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Parenting (id:14) ───────────────────────
  { id: 15, slug: "montessori-bedroom-ideas-toddler", keyword: "Montessori bedroom ideas for 2 year old", category_id: 14, language: "en", search_volume_estimate: 2900, trend_direction: S, trend_score: 52, competition_score: 16, opportunity_score: 81, result_count: 14000, top_domains: ["pinterest.com", "montessorimethod.com", "reddit.com"], content_suggestion: "Room-by-room Montessori setup guide: floor bed options, low shelf organization, independence-promoting layouts. Budget version under $200 and splurge version with furniture links.", related_keywords: ["Montessori toddler room", "floor bed Montessori", "Montessori playroom ideas", "toddler bedroom independence"], faq: [_faq("When to switch to a Montessori floor bed?", "Most families transition between 12-18 months when the child walks confidently. Ensure the entire room is fully baby-proofed first.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 71, slug: "screen-free-activities-for-toddlers", keyword: "screen free activities for toddlers at home easy", category_id: 14, language: "en", search_volume_estimate: 3700, trend_direction: U, trend_score: 64, competition_score: 13, opportunity_score: 87, result_count: 11000, top_domains: ["pinterest.com", "reddit.com", "busytoddler.com"], content_suggestion: "50+ screen-free toddler activities using household items. Organized by time needed (5 min prep, 15 min prep, 30+ min), age range, and skill developed. Printable activity cards.", related_keywords: ["toddler activities no screen", "indoor activities 2 year old", "easy sensory play ideas", "keeping toddler busy at home"], faq: [_faq("How much screen time is OK for a 2-year-old?", "The AAP recommends no more than 1 hour per day of high-quality programming for children 2-5, ideally co-viewed with a parent. For under 18 months, avoid screens other than video calls.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Fashion (id:15) ─────────────────────────
  { id: 16, slug: "capsule-wardrobe-2025-checklist", keyword: "capsule wardrobe 2025 checklist minimalist", category_id: 15, language: "en", search_volume_estimate: 5100, trend_direction: U, trend_score: 74, competition_score: 26, opportunity_score: 80, result_count: 23000, top_domains: ["pinterest.com", "youtube.com", "theminimalistvegan.com"], content_suggestion: "Season-by-season capsule wardrobe checklist: 37 pieces broken down by category. Style quiz, brand recommendations by budget, and a printable checklist PDF.", related_keywords: ["minimalist wardrobe guide", "how to build a capsule wardrobe", "capsule wardrobe pieces", "sustainable fashion basics"], faq: [_faq("How many pieces in a capsule wardrobe?", "A classic capsule has 30-40 items including tops, bottoms, outerwear, and shoes (not counting underwear and workout clothes). Seasonal capsules typically range from 30-37 pieces.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 72, slug: "best-sneakers-for-wide-feet-women", keyword: "best sneakers for wide feet women 2025 walking", category_id: 15, language: "en", search_volume_estimate: 2600, trend_direction: U, trend_score: 57, competition_score: 19, opportunity_score: 82, result_count: 15000, top_domains: ["reddit.com", "nordstrom.com", "zappos.com"], content_suggestion: "Top 12 sneakers for wide feet tested by women with 2E and 4E widths. Walking, running, and lifestyle categories. Fit guide with measurement instructions and brand-specific sizing differences.", related_keywords: ["wide width sneakers women", "comfortable walking shoes wide", "extra wide women shoes", "best sneakers for bunions"], faq: [_faq("Which sneaker brands offer wide widths for women?", "New Balance (2E, 4E available), ASICS (D width), Brooks (2E), Hoka (wide option), and Skechers (wide fit) consistently offer the most inclusive width options for women.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ═══════════════════════════════════════════════
  // 中文蓝海词库
  // ═══════════════════════════════════════════════

  // ── 跨境电商 / Business ──────────────────────
  { id: 101, slug: "kuajing-dianshang-xuanpin-gongju", keyword: "跨境电商选品工具推荐 2025 免费", category_id: 10, language: "zh", search_volume_estimate: 3600, trend_direction: U, trend_score: 82, competition_score: 25, opportunity_score: 80, result_count: 28000, top_domains: ["zhihu.com", "amz123.com", "cifnews.com"], content_suggestion: "对比2025年主流跨境电商选品工具：Jungle Scout vs Helium 10 vs Keepa vs 欧鹭，覆盖亚马逊、TikTok Shop、Temu三大平台。含免费替代方案和选品SOP流程图。", related_keywords: ["亚马逊选品方法", "跨境电商工具推荐", "Shopify选品", "TikTok爆品挖掘"], faq: [_faq("小卖家选品工具预算多少合适？", "新手可以从免费工具起步：Keepa免费版看价格历史，Google Trends看需求趋势，亚马逊Best Sellers看热销榜。月销$3000以下不建议买付费选品工具，先用免费数据源验证想法。")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },

  { id: 102, slug: "dulizhan-jianzhan-jiaocheng", keyword: "独立站建站教程 Shopify vs WooCommerce 新手", category_id: 10, language: "zh", search_volume_estimate: 5200, trend_direction: U, trend_score: 78, competition_score: 32, opportunity_score: 76, result_count: 41000, top_domains: ["zhihu.com", "shopify.com", "oyunqu.com"], content_suggestion: "从零搭建跨境电商独立站全流程：域名注册→Shopify/WooCommerce选型→支付接入（Stripe/PayPal/万里汇）→物流对接→SEO基础设置。含7天启动清单和费用明细表。", related_keywords: ["Shopify开店教程", "独立站收款方式", "WordPress建站教程", "跨境电商独立站 SEO"], faq: [_faq("Shopify和WooCommerce哪个更适合新手？", "Shopify上手更快（1天内可上线），月费$29起但功能全内置。WooCommerce免费但需要自己买服务器和配插件，技术门槛稍高但长期成本更低。建议新手先用Shopify验证产品，跑通后再考虑WooCommerce迁移。")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },

  { id: 103, slug: "xiaohongshu-yunying-jiqiao", keyword: "小红书运营技巧 涨粉 新手入门 2025", category_id: 10, language: "zh", search_volume_estimate: 12800, trend_direction: U, trend_score: 92, competition_score: 45, opportunity_score: 68, result_count: 98000, top_domains: ["xiaohongshu.com", "zhihu.com", "mp.weixin.qq.com"], content_suggestion: "小红书2025年最新算法解读：封面设计规范、标题公式、发布时间策略、关键词布局、薯条投放技巧。含20个爆款笔记拆解和30天起号计划表。", related_keywords: ["小红书涨粉技巧", "小红书爆文公式", "小红书变现方式", "小红书SEO优化"], faq: [_faq("小红书新号多久能起号？", "按照正确方法（垂直定位+日更+封面吸引力+关键词优化），新号通常2-4周能出第一篇爆文。关键是前30天坚持日更、研究对标账号的爆款选题、重视评论区互动。")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },

  { id: 104, slug: "fuye-xiangmu-tuijian", keyword: "2025副业推荐 不需要技术 在家就能做", category_id: 10, language: "zh", search_volume_estimate: 9600, trend_direction: U, trend_score: 88, competition_score: 50, opportunity_score: 63, result_count: 130000, top_domains: ["zhihu.com", "bilibili.com", "mp.weixin.qq.com"], content_suggestion: "整理20个零技术门槛副业项目：AI代写、小红书素人种草、Notion模板售卖、Etsy数字产品、远程客服、线上家教等。每个项目含启动成本、预期收益、时间投入和避坑指南。", related_keywords: ["在家赚钱的方法", "副业推荐无门槛", "自由职业入门", "被动收入项目"], faq: [_faq("零基础副业一个月能赚多少钱？", "前1-3个月通常只有500-2000元，因为需要学习技能和积累客户。坚持3-6个月后，认真做副业的普通人月入3000-8000是比较现实的目标。但要警惕那些承诺'月入10万'的项目，基本都是割韭菜。")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── AI工具 / Tech ────────────────────────────
  { id: 105, slug: "ai-xiezuo-gongju-paiming", keyword: "AI写作工具 中文 免费 哪个好用 2025", category_id: 5, language: "zh", search_volume_estimate: 8100, trend_direction: U, trend_score: 94, competition_score: 40, opportunity_score: 72, result_count: 75000, top_domains: ["zhihu.com", "sspai.com", "mp.weixin.qq.com"], content_suggestion: "横向评测2025年10款中文AI写作工具：Claude vs ChatGPT vs Kimi vs 通义千问 vs 文心一言 vs 豆包 vs DeepSeek。从文案、论文、公众号、小红书四个场景实测对比。", related_keywords: ["AI写文案工具", "免费AI写作", "ChatGPT中文写作", "AI生成文章工具"], faq: [_faq("中文AI写作哪个工具最好？", "如果是写公众号/小红书等短文案，Claude和Kimi的中文语感最好；如果是长文创作，DeepSeek性价比最高（免费且上下文长）。综合推荐：日常写作Claude，长文DeepSeek，创意文案Kimi。")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },

  { id: 106, slug: "ai-huihua-shengcheng-gongju", keyword: "AI绘画软件推荐 免费 中文版 2025", category_id: 5, language: "zh", search_volume_estimate: 6700, trend_direction: U, trend_score: 85, competition_score: 35, opportunity_score: 74, result_count: 55000, top_domains: ["bilibili.com", "zhihu.com", "xiaohongshu.com"], content_suggestion: "2025年主流AI绘画工具全对比：Midjourney vs Stable Diffusion vs DALL-E 3 vs 文心一格 vs 通义万相。含免费方案推荐、提示词写作技巧、商用版权说明。", related_keywords: ["AI生成图片工具", "Midjourney教程中文", "免费AI绘画", "AI绘图提示词"], faq: [_faq("AI绘画工具哪个免费又好用？", "通义万相和文心一格免费额度最大，适合中文场景。Stable Diffusion开源免费但需要自己部署（需要好显卡）。Midjourney效果最好但月费$10起。新手推荐先用通义万相练手，进阶再换Midjourney。")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },

  { id: 107, slug: "deepseek-shiyong-jiqiao", keyword: "DeepSeek使用技巧 高级玩法 prompt模板", category_id: 5, language: "zh", search_volume_estimate: 18400, trend_direction: U, trend_score: 98, competition_score: 30, opportunity_score: 82, result_count: 32000, top_domains: ["zhihu.com", "bilibili.com", "xiaohongshu.com"], content_suggestion: "DeepSeek深度使用指南：长文写作策略、代码生成技巧、数据分析prompt模板、文件上传功能挖掘、与其他AI工具联动的工作流。含50个实战prompt模板。", related_keywords: ["DeepSeek R1使用", "DeepSeek写代码", "DeepSeek高级功能", "AI prompt工程"], faq: [_faq("DeepSeek真的完全免费吗？", "是的，DeepSeek目前完全免费且无使用限制，支持128K上下文、文件上传、联网搜索。相比ChatGPT Plus($20/月)，在中文长文写作和代码生成任务上表现接近甚至更好。")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Food / 美食 ──────────────────────────────
  { id: 108, slug: "kongqizhaguo-shipu-daquan", keyword: "空气炸锅食谱大全 新手入门 简单又好吃", category_id: 4, language: "zh", search_volume_estimate: 7600, trend_direction: U, trend_score: 72, competition_score: 28, opportunity_score: 77, result_count: 38000, top_domains: ["xiachufang.com", "douyin.com", "xiaohongshu.com"], content_suggestion: "101道空气炸锅食谱：肉类、海鲜、蔬菜、甜点四大类。含温度时间对照表、新手避坑指南、食材处理技巧。每道菜标注难度和准备时间。", related_keywords: ["空气炸锅做什么好吃", "新手空气炸锅食谱", "空气炸锅甜点", "低脂空气炸锅菜"], faq: [_faq("空气炸锅需要预热吗？", "大部分空气炸锅预热2-3分钟后效果更好（外酥里嫩）。但厚切肉类和冷冻食品不需要预热——直接放进去反而能锁住水分。记住：薄的小块的预热，厚的冻的不预热。")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },

  { id: 109, slug: "jianfei-shipu-yizhou", keyword: "一周减肥食谱 学生党 低成本 不用节食", category_id: 4, language: "zh", search_volume_estimate: 5400, trend_direction: S, trend_score: 62, competition_score: 38, opportunity_score: 69, result_count: 62000, top_domains: ["xiaohongshu.com", "zhihu.com", "douyin.com"], content_suggestion: "人均20元/天的低成本减肥食谱：食堂/外卖减肥点餐攻略、便利店健康零食清单、宿舍可做的简易减脂餐。含热量计算表和一键生成周食谱模板。", related_keywords: ["学生减肥方法", "便宜减肥食谱", "不运动减肥食谱", "食堂减肥怎么吃"], faq: [_faq("学生党食堂怎么减肥？", "食堂减肥三步法：1）打菜前喝一碗清汤增加饱腹感；2）一荤两素白米饭减半；3）避开红烧、糖醋、油炸菜，多选清蒸、凉拌、水煮。这样吃一顿不到12元，热量控制在500卡内。")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Health / 健康 ────────────────────────────
  { id: 110, slug: "shimian-zhiyu-fangfa", keyword: "失眠怎么快速入睡 不用吃药 亲测有效", category_id: 2, language: "zh", search_volume_estimate: 9300, trend_direction: S, trend_score: 65, competition_score: 42, opportunity_score: 67, result_count: 85000, top_domains: ["zhihu.com", "mp.weixin.qq.com", "douyin.com"], content_suggestion: "8个非药物助眠方法实测：4-7-8呼吸法、渐进式肌肉放松、白噪音选择指南、睡前仪式设计、饮食调整。含30天睡眠改善计划表和睡眠日记模板。", related_keywords: ["快速入睡方法", "失眠自我调理", "改善睡眠质量", "睡前放松技巧"], faq: [_faq("4-7-8呼吸法真的有效吗？", "4-7-8呼吸法是哈佛大学Andrew Weil博士推广的技术（吸气4秒→屏息7秒→呼气8秒）。多项研究表明它能激活副交感神经系统、降低心率，对轻度焦虑性失眠有效率约60-70%。关键是需要每天坚持练习2周以上，不是即时生效的魔法。")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  { id: 111, slug: "jiaolv-zheng-zhiyu", keyword: "焦虑症自我调理方法 不用吃药 心理学", category_id: 2, language: "zh", search_volume_estimate: 7200, trend_direction: U, trend_score: 76, competition_score: 35, opportunity_score: 73, result_count: 48000, top_domains: ["zhihu.com", "jiandanxinli.com", "mp.weixin.qq.com"], content_suggestion: "基于CBT认知行为疗法的焦虑自我调理方案：认知重构练习、暴露疗法步骤、正念冥想入门、应急应对卡模板。区分正常焦虑和焦虑症的自测清单。", related_keywords: ["焦虑怎么缓解", "认知行为疗法入门", "正念冥想教程", "心理自救方法"], faq: [_faq("怎么判断是正常焦虑还是焦虑症？", "正常焦虑有明确原因（如考试、面试），事情过去就缓解。焦虑症的特征是：1）无缘无故持续紧张超过6个月；2）身体症状明显（心悸、手抖、失眠）；3）明显影响正常工作和社交。如果有后两点，建议去看心理科医生而非仅靠自我调理。")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Finance / 理财 ───────────────────────────
  { id: 112, slug: "jijin-dingtou-xinshou", keyword: "基金定投怎么买 新手入门 2025年推荐", category_id: 3, language: "zh", search_volume_estimate: 5800, trend_direction: S, trend_score: 58, competition_score: 48, opportunity_score: 60, result_count: 110000, top_domains: ["zhihu.com", "eastmoney.com", "mp.weixin.qq.com"], content_suggestion: "基金定投新手指南：宽基指数vs行业ETF选择、定投周期策略（周投vs月投数据对比）、止盈方法（目标收益法vs估值分位法）、主流平台费率对比。", related_keywords: ["基金定投策略", "指数基金推荐", "新手怎么买基金", "定投止盈方法"], faq: [_faq("月薪3000适合定投多少钱？", "建议月收入的10-15%，即300-450元/月。先从沪深300+中证500各一半开始，坚持定投不看短期波动。关键在于长期坚持（至少3-5年）和熊市不恐慌卖出。")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  { id: 113, slug: "geren-suo-de-shui-shenbao", keyword: "个人所得税申报流程 2025 退税攻略 自由职业", category_id: 3, language: "zh", search_volume_estimate: 4100, trend_direction: U, trend_score: 70, competition_score: 20, opportunity_score: 82, result_count: 15000, top_domains: ["chinatax.gov.cn", "zhihu.com", "mp.weixin.qq.com"], content_suggestion: "自由职业者/自媒体/远程工作者的个税申报完整指南：哪些收入需要申报、专项附加扣除详解（房租/房贷/赡养老人/继续教育）、退税技巧、APP操作截图教程。", related_keywords: ["个税退税攻略", "自由职业报税", "专项附加扣除", "个人所得税APP使用"], faq: [_faq("自由职业者怎么合法少交税？", "三个合法节税方式：1）充分利用专项附加扣除（房租+赡养老人+继续教育一年最多能省近万元）；2）注册个体户享受核定征收政策（综合税率可低至1-3%）；3）保留所有业务相关发票和收据用于成本抵扣。务必走合法途径，虚报和偷税风险极大。")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Education / 教育 ─────────────────────────
  { id: 114, slug: "jianlixiezuo-moban", keyword: "简历怎么写才能通过筛选 AI筛选简历技巧", category_id: 8, language: "zh", search_volume_estimate: 6500, trend_direction: U, trend_score: 74, competition_score: 33, opportunity_score: 72, result_count: 43000, top_domains: ["zhihu.com", "zhipin.com", "linkedin.cn"], content_suggestion: "针对大厂ATS系统优化的简历写作法：关键词策略、STAR法则实战、量化成果技巧、AI简历筛查原理。含10个行业模板和简历自检清单。", related_keywords: ["简历模板下载", "大厂简历技巧", "英文简历写作", "简历关键词优化"], faq: [_faq("为什么简历总是被筛掉？", "大公司收到的每份校招岗位简历平均只看6秒。被筛的三个常见原因：1）缺少JD里的关键词（HR系统自动过滤）；2）只有工作职责没有量化成果；3）格式太花哨机器解析不了。用STAR法则+数字量化+PDF纯文本格式能大幅提高通过率。")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  { id: 115, slug: "yingyu-xuexi-app-tuijian", keyword: "学英语app推荐 零基础 成年人 2025", category_id: 8, language: "zh", search_volume_estimate: 4800, trend_direction: S, trend_score: 60, competition_score: 38, opportunity_score: 67, result_count: 56000, top_domains: ["zhihu.com", "xiaohongshu.com", "douyin.com"], content_suggestion: "成年人零基础学英语APP深度评测：多邻国vs流利说vs薄荷阅读vs开言英语vs每日英语听力。针对听说读写分项推荐，含6个月从零到日常对话的学习路径规划。", related_keywords: ["成人英语学习", "零基础英语入门", "英语口语练习app", "免费学英语软件"], faq: [_faq("成年人零基础学英语还来得及吗？", "完全来得及。成年人学习语言的优势是理解和自律能力更强。关键是每天坚持30分钟+找到合适的难度起点+以'能用'为目标而非'完美'。推荐从多邻国+每日英语听力起步，每天坚持6个月就能进行简单日常对话。")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Pets / 宠物 ──────────────────────────────
  { id: 116, slug: "yangmao-xinshou-zhinan", keyword: "养猫新手必看 接猫准备 花费清单 2025", category_id: 1, language: "zh", search_volume_estimate: 3900, trend_direction: U, trend_score: 68, competition_score: 22, opportunity_score: 80, result_count: 18000, top_domains: ["zhihu.com", "xiaohongshu.com", "douyin.com"], content_suggestion: "新手养猫全攻略：接猫前准备清单、疫苗驱虫时间表、猫粮选购指南（进口vs国产）、猫砂测评、常见疾病预警信号。含首年花费明细表和月度预算模板。", related_keywords: ["第一次养猫", "小猫到家注意事项", "猫粮推荐性价比", "养猫一个月花多少钱"], faq: [_faq("养一只猫一个月大概花多少钱？", "基础养猫月均300-500元（猫粮150+猫砂50+驱虫100+零食/玩具100）。如果吃进口高端粮+定期体检+宠物保险，月均600-1000元。首年花费更高（疫苗+绝育+基础用品），约3000-5000元一次性投入。")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Travel / 旅行 ────────────────────────────
  { id: 117, slug: "guonei-lvyou-xianlu-tuijian", keyword: "国内旅游攻略 小众景点 人少 适合一个人去", category_id: 7, language: "zh", search_volume_estimate: 8400, trend_direction: U, trend_score: 80, competition_score: 42, opportunity_score: 70, result_count: 72000, top_domains: ["xiaohongshu.com", "mafengwo.cn", "douyin.com"], content_suggestion: "15个国内冷门旅行地推荐（避开网红景点的人挤人）：云南、贵州、川西、西北环线小众路线。含交通攻略、住宿推荐、人均花费和最佳旅行季节。", related_keywords: ["国内冷门景点", "一个人旅行推荐", "小众旅游地", "国内深度游攻略"], faq: [_faq("国内哪些地方适合一个人旅行？", "安全性高+交通便利+花费适中的首选：云南沙溪古镇（比大理安静）、福建泉州（千年古城+遍地美食）、贵州兴义（万峰林+马岭河峡谷）。这些地方商业化程度低、民风淳朴、单人间住宿好找且价格不贵。")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Home & DIY / 家居 ────────────────────────
  { id: 118, slug: "xiaohuxing-zhuangxiu-sheji", keyword: "小户型装修设计 40平 收纳 省钱 效果图", category_id: 6, language: "zh", search_volume_estimate: 6100, trend_direction: U, trend_score: 73, competition_score: 36, opportunity_score: 71, result_count: 49000, top_domains: ["xiaohongshu.com", "zhihu.com", "kujiale.com"], content_suggestion: "40-60平小户型装修实战：空间利用技巧（榻榻米/折叠家具/墙面收纳）、5万/10万/15万三档预算方案、装修避坑清单、水电改造注意事项。含3D效果图和施工流程。", related_keywords: ["小户型设计案例", "装修省钱技巧", "收纳空间设计", "自装流程攻略"], faq: [_faq("40平小户型装修要多少钱？", "简装（出租标准）约2-3万；中等装修（自住舒适）5-8万；精装（品质家居）10-15万。最大的省钱空间在：自己画设计图省设计费、不做复杂吊顶和背景墙、家具慢慢添置而非一次性买齐。")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── SEO / 站长工具 ───────────────────────────
  { id: 119, slug: "wangzhan-seo-youhua-jiaocheng", keyword: "网站SEO优化教程 新手入门 2025 Google排名", category_id: 5, language: "zh", search_volume_estimate: 4500, trend_direction: U, trend_score: 77, competition_score: 40, opportunity_score: 70, result_count: 55000, top_domains: ["zhihu.com", "mp.weixin.qq.com", "seo.com.cn"], content_suggestion: "2025年Google SEO完整教程：关键词研究方法、内容优化框架、外链建设策略、技术SEO基础、Core Web Vitals优化。含30天SEO行动计划表和免费工具清单。", related_keywords: ["Google SEO入门", "网站排名优化", "SEO关键词研究", "外链建设方法"], faq: [_faq("新网站多久能被Google收录？", "提交sitemap后通常1-4周内开始收录。排名则需要3-12个月（取决于关键词竞争度和内容质量）。关键是持续发布高质量内容+获得自然外链，新站不要急于求成买外链——Google会惩罚人工外链。")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },

  { id: 120, slug: "wangshelianmeng-zhuanqian", keyword: "网站联盟营销 Affiliate赚钱 中文教程 2025", category_id: 10, language: "zh", search_volume_estimate: 3200, trend_direction: U, trend_score: 78, competition_score: 18, opportunity_score: 85, result_count: 12000, top_domains: ["zhihu.com", "mp.weixin.qq.com", "reddit.com"], content_suggestion: "Affiliate营销中文实战教程：Amazon联盟vs ShareASale vs ClickBank平台对比、高佣金品类选择、内容型网站搭建流程、流量获取策略。含6个月从0到$1000/月的路线图。", related_keywords: ["联盟营销教程", "Amazon联盟赚钱", "佣金网站搭建", "被动收入英文站"], faq: [_faq("联盟营销还能赚钱吗？2025年竞争太激烈了吧？", "竞争确实比5年前大了，但机会仍然存在——关键变化在于：泛内容站现在很难活，但垂直niche的内容站（比如只写'骑行装备'或'宠物鱼饲养'）仍然有很多蓝海空间。选对细分领域+专注信息型内容+耐心等待排名，$1000/月是可实现的目标。")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
];
