import type { Category, Keyword } from "./types";

export const seedCategories: Category[] = [
  { id: 1, slug: "pets", name: "Pets", description: "Pet care, training, food, and supplies keywords", icon: "pets", keyword_count: 5, created_at: "2025-01-01" },
  { id: 2, slug: "health", name: "Health & Fitness", description: "Wellness, fitness, nutrition, and medical keywords", icon: "health", keyword_count: 5, created_at: "2025-01-01" },
  { id: 3, slug: "finance", name: "Finance", description: "Investing, saving, credit, and money management", icon: "finance", keyword_count: 5, created_at: "2025-01-01" },
  { id: 4, slug: "food", name: "Food & Cooking", description: "Recipes, cooking techniques, diets, and food reviews", icon: "food", keyword_count: 5, created_at: "2025-01-01" },
  { id: 5, slug: "tech", name: "Technology", description: "Software, gadgets, AI tools, and programming", icon: "tech", keyword_count: 5, created_at: "2025-01-01" },
  { id: 6, slug: "home", name: "Home & DIY", description: "Home improvement, decoration, and DIY projects", icon: "home", keyword_count: 5, created_at: "2025-01-01" },
  { id: 7, slug: "travel", name: "Travel", description: "Destinations, tips, gear, and travel planning", icon: "travel", keyword_count: 5, created_at: "2025-01-01" },
  { id: 8, slug: "education", name: "Education", description: "Online courses, learning resources, and study tips", icon: "education", keyword_count: 4, created_at: "2025-01-01" },
  { id: 9, slug: "beauty", name: "Beauty & Skincare", description: "Skincare, makeup, hair care, and beauty reviews", icon: "beauty", keyword_count: 4, created_at: "2025-01-01" },
  { id: 10, slug: "business", name: "Business & Marketing", description: "Entrepreneurship, marketing, and small business tips", icon: "business", keyword_count: 4, created_at: "2025-01-01" },
  { id: 11, slug: "sports", name: "Sports & Fitness", description: "Training, gear, and sports performance", icon: "sports", keyword_count: 4, created_at: "2025-01-01" },
  { id: 12, slug: "automotive", name: "Automotive", description: "Car maintenance, buying guides, and accessories", icon: "automotive", keyword_count: 3, created_at: "2025-01-01" },
  { id: 13, slug: "gardening", name: "Gardening", description: "Plants, landscaping, and garden care", icon: "gardening", keyword_count: 4, created_at: "2025-01-01" },
  { id: 14, slug: "parenting", name: "Parenting", description: "Baby care, child development, and family life", icon: "parenting", keyword_count: 4, created_at: "2025-01-01" },
  { id: 15, slug: "fashion", name: "Fashion", description: "Style guides, trends, and clothing reviews", icon: "fashion", keyword_count: 3, created_at: "2025-01-01" },
];

const S = "stable", U = "up", D = "down";
const _faq = (q: string, a: string) => ({ q, a });

export const seedKeywords: Keyword[] = [
  // ── Pets (id:1) ────────────────────────────
  { id: 1, slug: "diy-dog-wash-station", keyword: "DIY dog wash station for home", category_id: 1, language: "en", search_volume_estimate: 2400, trend_direction: U, trend_score: 72, competition_score: 15, opportunity_score: 89, result_count: 18000, top_domains: ["pinterest.com", "reddit.com", "youtube.com"], content_suggestion: "Step-by-step guide to building a homemade dog washing station with PVC pipes and a utility sink. Include cost breakdown, tools needed, and before/after photos.", related_keywords: ["homemade dog grooming station", "outdoor dog wash area", "dog bath station ideas", "DIY pet shower"], faq: [_faq("How much does it cost to build a DIY dog wash station?", "A basic DIY dog wash station typically costs $50–200 depending on materials. PVC pipe setups are the cheapest, while tiled stations with plumbing can run $200+.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 2, slug: "best-cat-food-sensitive-stomach", keyword: "best cat food for sensitive stomach vomiting", category_id: 1, language: "en", search_volume_estimate: 5400, trend_direction: S, trend_score: 65, competition_score: 22, opportunity_score: 82, result_count: 45000, top_domains: ["reddit.com", "chewy.com", "thesprucepets.com"], content_suggestion: "Vet-reviewed comparison of top 10 cat foods for sensitive stomachs. Include ingredient analysis, price per day, and a printable shopping guide.", related_keywords: ["limited ingredient cat food", "grain free cat food", "wet food for cats with IBS", "best dry food for digestive issues"], faq: [_faq("What ingredients cause stomach sensitivity in cats?", "Common triggers include grains like wheat and corn, artificial preservatives, dairy, and certain proteins like beef. Limited-ingredient diets help identify the trigger.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 51, slug: "puppy-training-schedule-by-age", keyword: "puppy training schedule by age week by week", category_id: 1, language: "en", search_volume_estimate: 3800, trend_direction: U, trend_score: 68, competition_score: 18, opportunity_score: 86, result_count: 15000, top_domains: ["akc.org", "reddit.com", "pinterest.com"], content_suggestion: "Week-by-week training milestones from 8 weeks to 1 year. Printable checklist for each stage covering potty training, commands, socialization, and leash walking.", related_keywords: ["8 week old puppy training", "puppy potty training schedule", "puppy socialization checklist", "dog training timeline"], faq: [_faq("At what age should puppy training start?", "Basic training can begin as early as 8 weeks old. Focus on socialization, potty training, and simple commands like 'sit' and 'come' in the first few weeks.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 52, slug: "homemade-dog-food-crockpot", keyword: "homemade dog food crockpot recipe vet approved", category_id: 1, language: "en", search_volume_estimate: 2100, trend_direction: U, trend_score: 60, competition_score: 12, opportunity_score: 87, result_count: 9000, top_domains: ["allrecipes.com", "pinterest.com", "youtube.com"], content_suggestion: "5 vet-approved slow cooker dog food recipes with nutritional breakdowns. Include ingredient substitutions for allergies and portion calculator by dog weight.", related_keywords: ["easy homemade dog food", "slow cooker pet food", "healthy dog food recipes", "DIY dog food nutrition"], faq: [_faq("Is homemade dog food healthier than kibble?", "Homemade dog food can be healthier when properly balanced with protein, carbs, and vegetables. However, it must include essential nutrients like calcium and taurine — consult your vet for a balanced recipe.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Health & Fitness (id:2) ─────────────────
  { id: 3, slug: "couch-to-5k-plan-for-seniors", keyword: "couch to 5K plan for seniors over 60", category_id: 2, language: "en", search_volume_estimate: 3200, trend_direction: U, trend_score: 78, competition_score: 8, opportunity_score: 93, result_count: 12000, top_domains: ["verywellfit.com", "reddit.com"], content_suggestion: "A 12-week running plan for seniors emphasizing joint safety, heart rate zones, and recovery. Include doctor-check tips, recommended shoes, and a printable progress tracker.", related_keywords: ["walking to running program seniors", "senior fitness plan", "running after 60", "safe running for older adults"], faq: [_faq("Is running safe for a 60-year-old beginner?", "Yes, with proper preparation. Consult your doctor, invest in good shoes, and start with brisk walking before introducing run intervals. Many seniors successfully complete C25K programs.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 53, slug: "intermittent-fasting-for-women-over-40", keyword: "intermittent fasting for women over 40 meal plan", category_id: 2, language: "en", search_volume_estimate: 6200, trend_direction: U, trend_score: 84, competition_score: 28, opportunity_score: 80, result_count: 38000, top_domains: ["healthline.com", "reddit.com", "mindbodygreen.com"], content_suggestion: "Hormone-aware intermittent fasting guide for perimenopausal women. 16:8 and 14:10 protocols with sample meal plans, supplement recommendations, and a 30-day kickstart calendar.", related_keywords: ["IF for menopause", "fasting over 40 female", "hormone balance diet plan", "best fasting schedule for women"], faq: [_faq("Does intermittent fasting work for women over 40?", "Yes, but timing matters. A 14:10 schedule is often gentler on hormones than 16:8 for perimenopausal women. Focus on protein-rich meals and avoid fasting during the week before your period.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 54, slug: "best-yoga-poses-for-back-pain", keyword: "best yoga poses for lower back pain beginners", category_id: 2, language: "en", search_volume_estimate: 8800, trend_direction: S, trend_score: 62, competition_score: 35, opportunity_score: 72, result_count: 92000, top_domains: ["yogajournal.com", "verywellfit.com", "healthline.com"], content_suggestion: "Illustrated guide to 10 gentle yoga poses for lower back pain. Each pose with modifications for limited mobility, safety warnings, and a 15-minute daily routine video script.", related_keywords: ["gentle yoga for back", "morning yoga routine", "yoga for sciatica", "stretches for back pain"], faq: [_faq("Which yoga poses should I avoid with lower back pain?", "Avoid deep forward folds, full wheel pose, and unsupported twists. Focus on cat-cow, child's pose, and gentle supine stretches. Always work within a pain-free range of motion.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Finance (id:3) ──────────────────────────
  { id: 4, slug: "high-dividend-etf-monthly-payout", keyword: "high dividend ETF monthly payout 2025", category_id: 3, language: "en", search_volume_estimate: 8100, trend_direction: U, trend_score: 85, competition_score: 30, opportunity_score: 78, result_count: 89000, top_domains: ["investopedia.com", "fool.com", "seekingalpha.com"], content_suggestion: "Curated list of monthly dividend ETFs with yield, expense ratio, and 5-year performance. Interactive comparison table and downloadable spreadsheet. Tax implications for non-US investors.", related_keywords: ["best monthly dividend ETFs", "high yield income ETFs", "monthly dividend stocks", "ETF with 5% yield"], faq: [_faq("Which ETF pays the highest monthly dividend?", "As of 2025, JEPI, JEPQ, and DIVO are among the highest-yielding monthly-pay ETFs with yields in the 7–10% range. Total return and expense ratio matter as much as yield.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 55, slug: "best-credit-card-for-freelancers", keyword: "best credit card for freelancers 2025 no annual fee", category_id: 3, language: "en", search_volume_estimate: 2700, trend_direction: U, trend_score: 71, competition_score: 20, opportunity_score: 83, result_count: 22000, top_domains: ["nerdwallet.com", "reddit.com", "forbes.com"], content_suggestion: "Compare top 8 no-annual-fee cards for freelancers: cashback on business expenses, virtual card features, expense tracking integrations, and 0% intro APR periods. Decision flowchart included.", related_keywords: ["freelancer banking tips", "self employed credit card", "business card no fee", "best cashback for freelancers"], faq: [_faq("Should freelancers get a business credit card?", "Yes, even sole proprietors benefit. Business cards separate personal and business expenses for tax time, often have higher credit limits, and may offer expense-management features useful for freelancers.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 56, slug: "how-to-build-emergency-fund-fast", keyword: "how to build an emergency fund fast on low income", category_id: 3, language: "en", search_volume_estimate: 4100, trend_direction: U, trend_score: 75, competition_score: 15, opportunity_score: 85, result_count: 18000, top_domains: ["reddit.com", "daveramsey.com", "thepennyhoarder.com"], content_suggestion: "Realistic 90-day plan to save $1000 emergency fund on a tight budget. Side hustle ideas ranked by effort-to-reward, automatic savings hacks, and a printable savings tracker.", related_keywords: ["save money fast", "emergency fund calculator", "low income savings plan", "how much emergency fund"], faq: [_faq("How much should I have in an emergency fund?", "Aim for 3–6 months of essential expenses. Start with a mini-goal of $1000, then build to one month of expenses, then expand from there. Any emergency fund is better than none.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Food & Cooking (id:4) ───────────────────
  { id: 5, slug: "sourdough-discard-crackers-recipe", keyword: "sourdough discard crackers recipe easy", category_id: 4, language: "en", search_volume_estimate: 9800, trend_direction: U, trend_score: 90, competition_score: 25, opportunity_score: 85, result_count: 56000, top_domains: ["kingarthurbaking.com", "pinterest.com", "theclevercarrot.com"], content_suggestion: "Ultimate guide to sourdough discard crackers with 5 flavor variations. Step-by-step photos, storage tips, and a video embed. Pairing suggestions for cheese boards.", related_keywords: ["sourdough discard recipes", "what to make with sourdough discard", "easy sourdough crackers", "no-waste sourdough ideas"], faq: [_faq("Can I freeze sourdough discard crackers?", "Yes, baked crackers freeze well for up to 3 months. You can also freeze the dough disc and bake fresh later.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 57, slug: "meal-prep-ideas-for-weight-loss", keyword: "healthy meal prep ideas for weight loss on a budget", category_id: 4, language: "en", search_volume_estimate: 7200, trend_direction: U, trend_score: 77, competition_score: 32, opportunity_score: 75, result_count: 61000, top_domains: ["eatingwell.com", "pinterest.com", "reddit.com"], content_suggestion: "Budget-friendly meal prep for weight loss: 5 complete weekly plans under $50 each. Calorie counts, grocery lists, container recommendations, and freezer-friendly options.", related_keywords: ["cheap meal prep", "low calorie meal prep", "weight loss lunch ideas", "budget healthy eating plan"], faq: [_faq("How long can meal prep food stay in the fridge?", "Most cooked meals stay fresh for 3–4 days refrigerated. Prep twice a week if you prefer fresher food, or freeze half the batch for later in the week.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 58, slug: "air-fryer-recipes-for-beginners", keyword: "easy air fryer recipes for beginners healthy", category_id: 4, language: "en", search_volume_estimate: 11500, trend_direction: U, trend_score: 88, competition_score: 38, opportunity_score: 70, result_count: 87000, top_domains: ["delish.com", "tasteofhome.com", "allrecipes.com"], content_suggestion: "25 beginner-friendly air fryer recipes organized by meal type. Cooking time cheat sheet for common foods, cleaning tips, and the 5 mistakes every new air fryer owner makes.", related_keywords: ["air fryer cooking guide", "quick air fryer meals", "healthy air fryer snacks", "air fryer vegetables recipe"], faq: [_faq("Do I need to preheat an air fryer?", "Most air fryers benefit from 2–3 minutes of preheating for crispier results. However, some models don't require it — check your manual. Generally, preheat for meats and frozen foods, skip for baked goods.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Tech (id:5) ─────────────────────────────
  { id: 6, slug: "cursor-ai-vs-copilot-2025", keyword: "Cursor AI vs GitHub Copilot 2025 comparison", category_id: 5, language: "en", search_volume_estimate: 6200, trend_direction: U, trend_score: 95, competition_score: 35, opportunity_score: 76, result_count: 67000, top_domains: ["medium.com", "reddit.com", "youtube.com"], content_suggestion: "Head-to-head comparison based on real coding tasks: autocomplete accuracy, refactoring quality, context understanding, and price. Side-by-side screenshots and a verdict table.", related_keywords: ["best AI coding assistant 2025", "Cursor AI review", "GitHub Copilot X", "AI code editor comparison"], faq: [_faq("Is Cursor better than GitHub Copilot?", "Cursor offers deeper IDE integration and context awareness for large codebases. Copilot has broader language support and a larger community. For full-stack work, many developers prefer Cursor in 2025.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 59, slug: "best-password-manager-for-families", keyword: "best password manager for families 2025 comparison", category_id: 5, language: "en", search_volume_estimate: 3500, trend_direction: S, trend_score: 55, competition_score: 25, opportunity_score: 74, result_count: 31000, top_domains: ["pcmag.com", "reddit.com", "cnet.com"], content_suggestion: "Family-focused password manager comparison: 1Password vs Bitwarden vs Dashlane vs NordPass. Evaluate sharing features, emergency access, child accounts, and price per user.", related_keywords: ["family password sharing", "best free password manager", "password security for families", "1Password family plan review"], faq: [_faq("Can families use a free password manager?", "Bitwarden's free plan supports unlimited devices and basic sharing. For family-specific features like emergency access and admin controls, 1Password Families ($4.99/month for 5) is the best value.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 60, slug: "how-to-speed-up-windows-11", keyword: "how to speed up Windows 11 laptop for free", category_id: 5, language: "en", search_volume_estimate: 9400, trend_direction: S, trend_score: 58, competition_score: 42, opportunity_score: 65, result_count: 102000, top_domains: ["tomshardware.com", "reddit.com", "windowscentral.com"], content_suggestion: "12 no-cost Windows 11 performance tweaks: startup programs, visual effects, background apps, disk cleanup, and power settings. Before/after benchmark data and a one-click PowerShell cleanup script.", related_keywords: ["Windows 11 slow fix", "speed up laptop free", "Windows 11 debloat script", "improve PC performance"], faq: [_faq("Why is Windows 11 so slow on my laptop?", "Common causes: too many startup programs, insufficient RAM (under 8GB), background apps, outdated drivers, or a nearly full SSD. The top 3 fixes — disable startup items, adjust visual effects, and free disk space — solve most cases.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Home & DIY (id:6) ───────────────────────
  { id: 7, slug: "small-bathroom-storage-rental", keyword: "small bathroom storage ideas for renters", category_id: 6, language: "en", search_volume_estimate: 4800, trend_direction: S, trend_score: 55, competition_score: 12, opportunity_score: 88, result_count: 21000, top_domains: ["pinterest.com", "apartmenttherapy.com", "reddit.com"], content_suggestion: "No-drill, landlord-friendly storage solutions by bathroom zone. Amazon product links, IKEA hacks, and a space calculator tool.", related_keywords: ["renter friendly organization", "over toilet storage", "small bathroom shelving", "apartment storage hacks"], faq: [_faq("How to add storage without drilling?", "Tension rods, over-the-door organizers, Command-brand adhesive hooks and shelves, freestanding units, and magnetic strips are all fully reversible options.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 61, slug: "how-to-paint-kitchen-cabinets", keyword: "how to paint kitchen cabinets without sanding", category_id: 6, language: "en", search_volume_estimate: 6700, trend_direction: U, trend_score: 73, competition_score: 20, opportunity_score: 82, result_count: 17000, top_domains: ["pinterest.com", "homedepot.com", "thisoldhouse.com"], content_suggestion: "Complete DIY guide to painting cabinets without sanding using liquid deglosser. Step-by-step video, best paint brands for cabinets, and a 3-day project timeline for a full kitchen.", related_keywords: ["cabinet painting DIY", "no sand cabinet refinish", "best paint for cabinets", "kitchen makeover budget"], faq: [_faq("Does painting cabinets without sanding really work?", "Yes, using a liquid deglosser (like Krud Kutter or Liquid Sandpaper) chemically etches the surface so primer and paint adhere. The finish won't be quite as durable as sanding, but it's 80% of the result for 20% of the effort.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 62, slug: "diy-accent-wall-ideas-bedroom", keyword: "DIY accent wall ideas for bedroom on a budget", category_id: 6, language: "en", search_volume_estimate: 3900, trend_direction: U, trend_score: 66, competition_score: 14, opportunity_score: 86, result_count: 12000, top_domains: ["pinterest.com", "youtube.com", "bhg.com"], content_suggestion: "10 accent wall projects under $100: peel-and-stick wallpaper, wood slats, paint techniques, and board-and-batten. Material lists, time estimates, and rental-friendly removable options.", related_keywords: ["bedroom accent wall paint", "cheap wall decor ideas", "wood slat wall DIY", "peel and stick wallpaper"], faq: [_faq("What is the cheapest way to create an accent wall?", "Paint is the most affordable option at $30-50 for a feature wall. Peel-and-stick wallpaper runs $40-80 for an accent wall. The most impact for the least money: a geometric painted design using painter's tape.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Travel (id:7) ───────────────────────────
  { id: 8, slug: "workation-visa-digital-nomad-2025", keyword: "workation visa digital nomad 2025 countries", category_id: 7, language: "en", search_volume_estimate: 3700, trend_direction: U, trend_score: 82, competition_score: 28, opportunity_score: 79, result_count: 34000, top_domains: ["nomadlist.com", "reddit.com", "thepointsguy.com"], content_suggestion: "Updated 2025 list of digital nomad visa countries with requirements, costs, income thresholds, and tax implications. Comparison table and country-matching quiz.", related_keywords: ["best countries for digital nomads", "nomad visa requirements", "cheapest nomad visa", "remote work visa Europe"], faq: [_faq("Which country has the easiest digital nomad visa?", "Portugal's D8 and Spain's digital nomad visa are among the most accessible, requiring proof of about $3,000/month. Estonia and Croatia also have streamlined online applications.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 63, slug: "budget-travel-japan-itinerary", keyword: "Japan travel itinerary 2 weeks budget 2025", category_id: 7, language: "en", search_volume_estimate: 5500, trend_direction: U, trend_score: 80, competition_score: 30, opportunity_score: 77, result_count: 39000, top_domains: ["reddit.com", "japan-guide.com", "youtube.com"], content_suggestion: "Detailed 14-day Japan itinerary on a $100/day budget. Tokyo-Kyoto-Osaka route with JR Pass calculations, budget hotel picks, affordable food spots, and hidden gems beyond the tourist trail.", related_keywords: ["Japan budget trip", "Tokyo to Kyoto route", "cheap Japan travel tips", "2 week Asia itinerary"], faq: [_faq("How much does a 2-week trip to Japan cost?", "Budget travelers can do Japan for $1,400-2,000 total per person excluding flights. Key savings: JR Pass for long-distance trains, business hotels instead of tourist hotels, and konbini/conveyor-belt meals.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 64, slug: "best-travel-insurance-for-seniors", keyword: "best travel insurance for seniors over 70 with pre-existing conditions", category_id: 7, language: "en", search_volume_estimate: 1800, trend_direction: U, trend_score: 63, competition_score: 10, opportunity_score: 90, result_count: 8000, top_domains: ["squaremouth.com", "reddit.com", "aarp.org"], content_suggestion: "Compare 6 insurers that cover travelers 70+ with pre-existing conditions. Medical evacuation limits, stability-period rules, and a plain-English explanation of what pre-existing condition waivers actually cover.", related_keywords: ["senior travel medical insurance", "over 70 travel cover", "pre-existing condition travel insurance", "best travel insurance for elderly"], faq: [_faq("Can an 80-year-old get travel insurance?", "Yes, several insurers like Allianz, GeoBlue, and Seven Corners offer policies for travelers 80+. Premiums are higher and pre-existing condition coverage requires purchasing within 14-21 days of your first trip payment.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Education (id:8) ────────────────────────
  { id: 9, slug: "notion-template-student-planner", keyword: "free Notion template for student planner", category_id: 8, language: "en", search_volume_estimate: 6600, trend_direction: U, trend_score: 76, competition_score: 20, opportunity_score: 84, result_count: 28000, top_domains: ["reddit.com", "youtube.com", "notion.so"], content_suggestion: "Curated roundup of 15 free Notion student templates with screenshots, setup times, and pros/cons. Tutorial on customization.", related_keywords: ["best Notion templates for college", "Notion student dashboard", "aesthetic Notion templates", "Notion for university"], faq: [_faq("Are free Notion templates worth it?", "Yes, many free templates from experienced creators match paid quality. Start with the official Notion gallery, then check Gumroad and Reddit for community-made options.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 65, slug: "best-online-course-platforms-for-creators", keyword: "best online course platforms for creators 2025 comparison", category_id: 8, language: "en", search_volume_estimate: 3100, trend_direction: U, trend_score: 70, competition_score: 34, opportunity_score: 71, result_count: 48000, top_domains: ["teachable.com", "thinkific.com", "reddit.com"], content_suggestion: "Teachables vs Thinkific vs Kajabi vs Podia vs Gumroad head-to-head. Fee comparison calculator, student-experience walkthrough screenshots, and a launch checklist.", related_keywords: ["sell courses online", "course platform fees", "best LMS for creators", "Kajabi vs Teachable"], faq: [_faq("Which course platform has the lowest fees?", "Gumroad charges no monthly fee but takes 10% per sale. Teachable's free plan takes $1 + 10%. Thinkific has a free plan with 0% transaction fees but limited features. For serious creators, Thinkific's free tier is the best deal.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Beauty (id:9) ───────────────────────────
  { id: 10, slug: "korean-skincare-routine-oily-skin", keyword: "Korean skincare routine for oily skin beginners", category_id: 9, language: "en", search_volume_estimate: 7800, trend_direction: S, trend_score: 60, competition_score: 32, opportunity_score: 73, result_count: 52000, top_domains: ["sokoglam.com", "peachandlily.com", "reddit.com"], content_suggestion: "Adapted 10-step Korean routine for oily skin with drugstore alternatives for every product. Morning vs evening cheat sheet and ingredient checklist.", related_keywords: ["Korean skincare oily acne", "best Korean moisturizer oily", "glass skin routine oily", "Korean skincare combination"], faq: [_faq("Can oily skin do the full 10-step routine?", "Yes, with lightweight gel-based products and no heavy creams. Focus on double cleansing, BHA exfoliation, and oil-free hydration. 5-7 steps are often enough for oily skin.")], is_trending: true, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 66, slug: "best-retinol-for-beginners-sensitive-skin", keyword: "best retinol serum for beginners with sensitive skin", category_id: 9, language: "en", search_volume_estimate: 4200, trend_direction: U, trend_score: 69, competition_score: 24, opportunity_score: 81, result_count: 27000, top_domains: ["reddit.com", "paulaschoice.com", "dermstore.com"], content_suggestion: "Gentle retinol guide for sensitive skin: 8 products ranked by irritation potential, the sandwich method explained, and a 12-week ramp-up calendar. Include bakuchiol as a plant-based alternative.", related_keywords: ["gentle retinol for sensitive skin", "retinol sandwich method", "beginners guide to retinoids", "best drugstore retinol 2025"], faq: [_faq("How often should beginners use retinol?", "Start once every 3 nights for the first 2 weeks, then every other night for 2 weeks, then nightly if tolerated. The sandwich method (moisturizer-retinol-moisturizer) significantly reduces irritation.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Business (id:10) ────────────────────────
  { id: 11, slug: "ai-marketing-automation-small-business", keyword: "AI marketing automation for small business 2025", category_id: 10, language: "en", search_volume_estimate: 4200, trend_direction: U, trend_score: 88, competition_score: 40, opportunity_score: 71, result_count: 78000, top_domains: ["hubspot.com", "zapier.com", "forbes.com"], content_suggestion: "AI tools for email, social scheduling, customer segmentation, and chatbots — all under $50/month. Tools comparison matrix and 30-day implementation roadmap.", related_keywords: ["small business marketing tools", "AI email marketing", "best chatbots small business", "automated social posting AI"], faq: [_faq("How much does AI marketing automation cost?", "Start with free tiers: Mailchimp for email, Buffer for social, Tidio for chat. A full AI-powered stack runs $50-150/month, far less than hiring a marketing team.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 67, slug: "how-to-start-a-newsletter", keyword: "how to start a newsletter and make money 2025", category_id: 10, language: "en", search_volume_estimate: 5100, trend_direction: U, trend_score: 79, competition_score: 36, opportunity_score: 73, result_count: 56000, top_domains: ["substack.com", "reddit.com", "convertkit.com"], content_suggestion: "Complete newsletter launch guide: niche selection framework, platform comparison (Substack vs ConvertKit vs beehiiv), growth tactics for the first 1000 subscribers, and 5 monetization models.", related_keywords: ["start a paid newsletter", "grow email list fast", "newsletter monetization tips", "best newsletter platforms"], faq: [_faq("Can you really make money with a newsletter?", "Yes. Direct revenue models include paid subscriptions (Substack), sponsorships ($25-250 CPM depending on niche), affiliate marketing, and selling your own products. Many creators reach $1k/month within 6-12 months of consistent publishing.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Sports (id:11) ──────────────────────────
  { id: 12, slug: "resistance-band-workout-plan-pdf", keyword: "resistance band workout plan PDF free", category_id: 11, language: "en", search_volume_estimate: 5600, trend_direction: S, trend_score: 58, competition_score: 18, opportunity_score: 83, result_count: 19000, top_domains: ["pinterest.com", "muscleandstrength.com", "reddit.com"], content_suggestion: "Printable 8-week resistance band program with exercise illustrations. Beginner, intermediate, and advanced tracks plus nutrition add-on.", related_keywords: ["full body band workout", "free workout plan PDF", "resistance band exercises chart", "home workout band only"], faq: [_faq("Can you build muscle with only resistance bands?", "Yes, bands provide variable resistance effective for building muscle. Progressive overload is achieved with thicker bands, more reps, or adjusted anchor points.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 68, slug: "home-gym-setup-small-space", keyword: "home gym setup ideas for small space budget 2025", category_id: 11, language: "en", search_volume_estimate: 4500, trend_direction: U, trend_score: 74, competition_score: 22, opportunity_score: 81, result_count: 18000, top_domains: ["reddit.com", "garagegymreviews.com", "youtube.com"], content_suggestion: "Build a functional home gym in 50 sq ft for under $500. Essential equipment ranked by versatility, storage hacks for apartments, and 3 full-body workout routines using minimal gear.", related_keywords: ["small home gym equipment", "apartment workout space", "budget gym setup", "compact exercise equipment"], faq: [_faq("What is the best first piece of home gym equipment?", "Adjustable dumbbells (like PowerBlock or Bowflex) offer the most versatility per square foot and dollar. A close second is a quality pull-up bar with resistance bands for a complete setup under $200.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Automotive (id:12) ──────────────────────
  { id: 13, slug: "ev-battery-replacement-cost-2025", keyword: "EV battery replacement cost 2025 by model", category_id: 12, language: "en", search_volume_estimate: 4400, trend_direction: U, trend_score: 70, competition_score: 45, opportunity_score: 65, result_count: 43000, top_domains: ["recurrentauto.com", "tesla.com", "caranddriver.com"], content_suggestion: "Battery replacement costs for Tesla, Leaf, Bolt, Kona, Mustang Mach-E. Warranty coverage, third-party vs dealer pricing, and battery-life extension tips.", related_keywords: ["Tesla battery replacement cost", "EV battery lifespan", "EV warranty coverage", "cheapest EV battery replacement"], faq: [_faq("How much does EV battery replacement cost?", "In 2025, replacement ranges from $3,000-7,000 for older Nissan Leafs to $12,000-20,000 for Tesla Model S/X. Most modern EVs have 8-year/100,000-mile warranties covering replacement below 70% capacity.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 69, slug: "best-dash-cam-for-night-driving", keyword: "best dash cam for night driving 2025 under 200", category_id: 12, language: "en", search_volume_estimate: 2300, trend_direction: U, trend_score: 67, competition_score: 16, opportunity_score: 84, result_count: 12000, top_domains: ["reddit.com", "youtube.com", "blackboxmycar.com"], content_suggestion: "Night-performance dash cam comparison with real footage comparisons. Installation guide for clean wiring, parking mode setup, and SD card recommendations.", related_keywords: ["best budget dash cam", "night vision dash cam", "dash cam with parking mode", "front and rear dash cam"], faq: [_faq("What makes a dash cam good at night?", "Look for a Sony STARVIS sensor, wide aperture (f/1.8 or lower), and HDR/WDR processing. The VIOFO A119 and Vantrue N4 are consistently ranked as top performers for nighttime clarity under $200.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Gardening (id:13) ───────────────────────
  { id: 14, slug: "raised-garden-bed-vegetable-layout", keyword: "raised garden bed vegetable layout planner", category_id: 13, language: "en", search_volume_estimate: 3300, trend_direction: U, trend_score: 68, competition_score: 14, opportunity_score: 86, result_count: 15000, top_domains: ["almanac.com", "pinterest.com", "reddit.com"], content_suggestion: "Interactive companion planting guide with seasonal rotation plans. Printable layout templates for 4x4, 4x8, and 3x6 beds plus beginner's veggie selection by climate zone.", related_keywords: ["raised bed planting guide", "companion planting chart", "square foot gardening", "vegetable garden planner"], faq: [_faq("What vegetables should not be planted together?", "Avoid planting tomatoes with potatoes, onions with beans, dill with carrots, and fennel with almost anything. Use a companion planting chart for best results.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 70, slug: "indoor-herb-garden-apartment", keyword: "indoor herb garden for apartment beginners no sunlight", category_id: 13, language: "en", search_volume_estimate: 2800, trend_direction: U, trend_score: 71, competition_score: 11, opportunity_score: 89, result_count: 9000, top_domains: ["pinterest.com", "reddit.com", "apartmenttherapy.com"], content_suggestion: "Set up an indoor herb garden in a low-light apartment using grow lights. 8 herbs that thrive indoors, recommended LED setups under $40, watering schedule, and harvesting tips.", related_keywords: ["grow herbs indoors apartment", "best indoor grow lights", "low light herbs kitchen", "beginner herb garden kit"], faq: [_faq("What herbs grow best indoors without sunlight?", "Mint, chives, parsley, and cilantro are the most shade-tolerant culinary herbs. With a budget LED grow light ($20-40), you can also grow basil, oregano, and thyme successfully indoors.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Parenting (id:14) ───────────────────────
  { id: 15, slug: "montessori-bedroom-ideas-toddler", keyword: "Montessori bedroom ideas for 2 year old", category_id: 14, language: "en", search_volume_estimate: 2900, trend_direction: S, trend_score: 52, competition_score: 16, opportunity_score: 81, result_count: 14000, top_domains: ["pinterest.com", "montessorimethod.com", "reddit.com"], content_suggestion: "Room-by-room Montessori setup guide: floor bed options, low shelf organization, independence-promoting layouts. Budget version under $200 and splurge version with furniture links.", related_keywords: ["Montessori toddler room", "floor bed Montessori", "Montessori playroom ideas", "toddler bedroom independence"], faq: [_faq("When to switch to a Montessori floor bed?", "Most families transition between 12-18 months when the child walks confidently. Ensure the entire room is fully baby-proofed first.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 71, slug: "screen-free-activities-for-toddlers", keyword: "screen free activities for toddlers at home easy", category_id: 14, language: "en", search_volume_estimate: 3700, trend_direction: U, trend_score: 64, competition_score: 13, opportunity_score: 87, result_count: 11000, top_domains: ["pinterest.com", "reddit.com", "busytoddler.com"], content_suggestion: "50+ screen-free toddler activities using household items. Organized by time needed (5 min prep, 15 min prep, 30+ min), age range, and skill developed. Printable activity cards.", related_keywords: ["toddler activities no screen", "indoor activities 2 year old", "easy sensory play ideas", "keeping toddler busy at home"], faq: [_faq("How much screen time is OK for a 2-year-old?", "The AAP recommends no more than 1 hour per day of high-quality programming for children 2-5, ideally co-viewed with a parent. For under 18 months, avoid screens other than video calls.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },

  // ── Fashion (id:15) ─────────────────────────
  { id: 16, slug: "capsule-wardrobe-2025-checklist", keyword: "capsule wardrobe 2025 checklist minimalist", category_id: 15, language: "en", search_volume_estimate: 5100, trend_direction: U, trend_score: 74, competition_score: 26, opportunity_score: 80, result_count: 23000, top_domains: ["pinterest.com", "youtube.com", "theminimalistvegan.com"], content_suggestion: "Season-by-season capsule wardrobe checklist: 37 pieces broken down by category. Style quiz, brand recommendations by budget, and a printable checklist PDF.", related_keywords: ["minimalist wardrobe guide", "how to build a capsule wardrobe", "capsule wardrobe pieces", "sustainable fashion basics"], faq: [_faq("How many pieces in a capsule wardrobe?", "A classic capsule has 30-40 items including tops, bottoms, outerwear, and shoes (not counting underwear and workout clothes). Seasonal capsules typically range from 30-37 pieces.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
  { id: 72, slug: "best-sneakers-for-wide-feet-women", keyword: "best sneakers for wide feet women 2025 walking", category_id: 15, language: "en", search_volume_estimate: 2600, trend_direction: U, trend_score: 57, competition_score: 19, opportunity_score: 82, result_count: 15000, top_domains: ["reddit.com", "nordstrom.com", "zappos.com"], content_suggestion: "Top 12 sneakers for wide feet tested by women with 2E and 4E widths. Walking, running, and lifestyle categories. Fit guide with measurement instructions and brand-specific sizing differences.", related_keywords: ["wide width sneakers women", "comfortable walking shoes wide", "extra wide women shoes", "best sneakers for bunions"], faq: [_faq("Which sneaker brands offer wide widths for women?", "New Balance (2E, 4E available), ASICS (D width), Brooks (2E), Hoka (wide option), and Skechers (wide fit) consistently offer the most inclusive width options for women.")], is_trending: false, last_updated: "2025-05-14", created_at: "2025-05-01" },
];
